version: '3.8'

services:
  db:
    container_name: smart_condo_db
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: smart_condo
    ports:
      - 5432:5432
